platform :ios, '13.0'

use_frameworks!

target 'ZQFlexibleToolExample' do
  pod 'TangramKit', '1.4.2'
  pod 'ZQFlexibleTool', :path => '..'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
